### ISSUE TITLE
Docs: broken link(s) to Deis blog

### ISSUE THREAD

**Issue by kingdonb** [teamhephy/workflow#106]
kingdonb/teamhephy-info#6 was reported by pd in the slack, broken link from the docs to the old Deis blog.  The page with the broken link is https://teamhephy.info/docs/workflow/applications/inter-app-communication/

@bacongobbler I've been quietly gathering permission of individual contributors to the Deis blog to republish posts, can I have your permission to republish articles onto blog.teamhephy.info if they have you listed as the author?

There was also a CI step in the old publishing pipeline that checked for broken links in the docs, I'm going to run that by hand before we close this, so perhaps we can clean up all the broken links in the docs pages before the next release.

**Comment by Cryptophobia** [comment]
Thanks for working on this @kingdonb . Can you  only post the blog posts that you have permission from the old authors?

Is it possible to post them with an old date of publishing and a notice at the top that this is not Hephy content and it will be removed if any copyrights are violated. With an email team@teamhephy.com as the point of contact. Just want to be safe! Thanks.

**Comment by bacongobbler** [comment]
I'm not sure I'm the right person to ask for permission on this one. You may want to reach out to Gabe for this one.

**Comment by kingdonb** [comment]
@bacongobbler I don't think there's any one person who can grant permission for all the authors.  Sorry I left for a while and didn't respond... I was just asking about articles that you personally contributed, I'll reach out to Gabe as well though.

So far all of the individual contributors I've reached out to have been really helpful and more than glad to hear their posts weren't all lost forever!

**Comment by bacongobbler** [comment]
Oh! If you're just looking for permission to republish content I wrote, then sure :)

**Comment by ChillarAnand** [comment]
There are few other broken links in docs.
https://docs.teamhephy.com/quickstart/users/ssh-keys/
https://docs.teamhephy.com/quickstart/applications/using-buildpacks
https://slack.deis.io/

**Comment by ChillarAnand** [comment]
Ignore the above comment. Looks like broken links are fixed in the master branch.

**Comment by Cryptophobia** [comment]
Closing this for now. :smiley_cat:
