### ISSUE TITLE
ssh_exchange_identification: read: Connection reset by peer

### ISSUE THREAD

**Issue by eugenewww** [teamhephy/workflow#107]
```
$ git push deis-staging master
ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.
```
Workflow was installed 2 years ago on GKE. How can I debug it and resolve the issue? This issue happened several days ago.

**Comment by eugenewww** [comment]
Looks like this issue is related to teamhephy/builder. Should I open the issue there and close it here?

**Comment by Cryptophobia** [comment]
Looks like an ssh connectivity problem. Can you check the SSH key that you are using is valid in pushing to the git deis-builder remote?

Also, it could be that the IP or domain has not changed for the deis-builder git remote.

```
git remote get-url deis-staging
```

Another thing to check is to see if the deis remote is correct and the name of the app is still correct in the above output.

Also check if the deis-builder is up and running.

```
kubectl get pods -n deis | grep -i "deis-builder"
```

**Comment by eugenewww** [comment]
Hi @Cryptophobia. Key is correct. Remote is correct. I can't deploy changes for any app. No one from my team can do it too. 
```
$ kubectl get pods -n deis | grep -i "deis-builder"
deis-builder-1364651073-tmkzz                            0/1     CrashLoopBackOff   2107       548d
```

<img width="1284" alt="Снимок экрана 2019-11-17 в 18 44 26" src="https://user-images.githubusercontent.com/56440163/69009852-b66cfa00-096a-11ea-8db8-48dbd28ae9d3.png">
<img width="1365" alt="Снимок экрана 2019-11-17 в 18 44 56" src="https://user-images.githubusercontent.com/56440163/69009853-b7059080-096a-11ea-9080-3775439d9b7b.png">
<img width="1206" alt="Снимок экрана 2019-11-17 в 18 45 59" src="https://user-images.githubusercontent.com/56440163/69009854-b7059080-096a-11ea-94b8-67ff72420d6e.png">

**Comment by eugenewww** [comment]
`$ kubectl --namespace=deis logs deis-builder-1364651073-tmkzz
2019/11/17 19:29:17 Error creating storage driver (googleapi: got HTTP response code 400 with body: )`

**Comment by Cryptophobia** [comment]
This seems to be the same error some users are experiencing with deis-builder on off-cluster Google Storage objectstore. Some of them have migrated to S3 in order to mitigate the issue while it is being investigated by the Google Cloud support team. 

Are you able to join our Slack channel and see what the latest is on this issue? https://slack.teamhephy.com

**Comment by eugenewww** [comment]
@Cryptophobia thanks.

**Comment by Cryptophobia** [comment]
Haven't heard any more information related to this issue so I will go ahead and close it for now. Join our Slack or report another issue if this persists.
