### ISSUE TITLE
Unable to install onto Kubernetes 1.18.3

### ISSUE THREAD

**Issue by coder36** [teamhephy/workflow#126]
I'm unable to install deis onto a fresh kubernetes cluster.   

```
helm  install hephy/workflow --namespace deis --generate-name

Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]
```

Versions:
```
kubectl --kubeconfig version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:50:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Any ideas ?  

thanks in advance
Mark

**Comment by kingdonb** [comment]
Thanks for the report! We are still supporting it, but for the time being if you want to use a supported version of Kubernetes (>= v1.16.x) then you need to enable some deprecated API versions

You can use a version earlier than 1.16 if that's an option for you, or you can... sec let me find the hint you give to kubelet when it starts with `--runtime-config` for K8s >v1.16.x and Workflow

```
--runtime-config=extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true
```

This is not ideal, we have a lot of PRs to merge and test to make sure this is addressed, and the next version of Hephy Workflow v2.22 will resolve this permanently.

**Comment by Cryptophobia** [comment]
This has been fixed in the latest version of Hephy Workflow v2.22.1
