### ISSUE TITLE
builds of CLI should match the current Workflow release

### ISSUE THREAD

**Issue by kingdonb** [teamhephy/workflow#68]
The current release of Hephy Workflow is v2.19.4, but the current CLI binary is still "deis" v2.18.0

(reference: issue against Workflow Docs to update URL that retrieves `install-v2.sh`, which knows where to get the "deis" cli api client binary. #69)

**Comment by kingdonb** [comment]
This needs to trigger a new docs release as well.

(I'll update teamhephy.info as soon as I can remember how exactly I deployed it.)

**Comment by kingdonb** [comment]
Maybe I have time to add some more updates to the docs repo first, since docs are not on CI, that way we can resolve and merge all docs issues all at once

**Comment by kingdonb** [comment]
src/roadmap/releases.md should reflect the reality of the latest workflow-cli release...

Right now it seems to have v2.18.0 hardcoded in there, I'm not sure if that's something we did, but I think I remember this update being automated as part of the jenkins jobs.

**Comment by kingdonb** [comment]
Oh, it doesn't need to have the version in there at all, if we maintain the script and "latest" in working order.  This is something CI would take care of for us.

Our workflow-cli hasn't changed since v2.18.0 anyway, it'll be time for a new release if it isn't already, since the router has new features, and the "services" stuff eg. teamhephy/workflow-cli#33 that goes with teamhephy/router#29 I think hasn't made it into any release yet.

**Comment by Cryptophobia** [comment]
The new CLI for v2.20.0 is live and we also have a Windows cross-compiled CLIs. The new v2.20.0 CLIs can be found here:

https://github.com/teamhephy/workflow-cli/releases

To install directly on the system:

```
wget https://raw.githubusercontent.com/teamhephy/workflow-cli/master/install-v2.sh &&
chmod +x install-v2.sh && ./install-v2.sh 
```
