### ISSUE TITLE
charts.deis.com

### ISSUE THREAD

**Issue by kingdonb** [teamhephy/workflow#84]
https://docs.teamhephy.info/installing-workflow/configuring-object-storage/#step-3-add-deis-repo

bad link, charts.deis.com is gone

**Comment by Cryptophobia** [comment]
Would you like to PR a fix for this?

**Comment by kingdonb** [comment]
Yes, I will definitely!

**Comment by kingdonb** [comment]
There is #88 for review.

If there are any other docs changes we want, let's wrap it up into that PR #88 so we only have to roll the docs sites once.
