### ISSUE TITLE
Automated release of workflow/docs

### ISSUE THREAD

**Issue by kingdonb** [teamhephy/workflow#96]
The docs build/release process is not continuous or streamlined, but [these four commits](https://github.com/kingdonb/workflow/tree/docs-deploy-basic-rebased) are my hints and will be rebased against this repo [teamhephy/workflow](//github.com/teamhephy/workflow) repo the next time I rebuild docs.

It only takes a couple of minutes to do a release, and is easier than writing new automation for now.  (But we need to automate it.)

If you know something that needs to change in the jekyll sources, please submit a PR against teamhephy/workflow!  Otherwise, I will take a look at what you suggest and try to implement it.

_Originally posted by @kingdonb in https://github.com/teamhephy/workflow/issues/91#issuecomment-489490332_

**Comment by Cryptophobia** [comment]
This is pretty streamlined for now for now even as a manual process. As far as automation goes all we have to do is:

Pre-requisites: Install mkdocs with python3 and pip3.

Step 1: Make build inside the workflow repo.
```
make build
```

Step 2: Copy all of the files from the _build folder into the hephy-docs repository:
```
cp _build/* ../hephy-docs/. 
```

Step 3: Push the hephy-docs repository to deis remote:
```
git push deis master
```

**Comment by kingdonb** [comment]
Thank you for the straightforward guide!

I think we should do this as a containerized process, but for now I am still using my own semi-straightforward (different) process to update docs.teamhephy.info, which works with the heroku-buildpack-static upstream buildpack, I prefer this to the Dockerfile version

In it, I have added:

```
diff --git a/.buildpacks b/.buildpacks
new file mode 100644
index 00000000..fb3f0127
--- /dev/null
+++ b/.buildpacks
@@ -0,0 +1 @@
+https://github.com/heroku/heroku-buildpack-static.git
```

A file, `static.json` for configuration:

```
diff --git a/static.json b/static.json
new file mode 100644
index 00000000..48c60c62
--- /dev/null
+++ b/static.json
@@ -0,0 +1,3 @@
+{
+  "root": "html/"
+}
```

Deleted the Dockerfile, so a Ruby process in memory is not used (we use nginx instead):

```
diff --git a/Dockerfile b/Dockerfile
deleted file mode 100644
index e25ae7da..00000000
--- a/Dockerfile
+++ /dev/null
@@ -1,9 +0,0 @@
-FROM python:3.5.1-alpine
-
-COPY . /app
-WORKDIR /app
-
-RUN pip install -r requirements.txt
-
-EXPOSE 8000
-CMD ["mkdocs", "serve", "-a", "0.0.0.0:8000"]
```

And, in the last (disposable) commit, the output of `mkdocs build` is made available to the nginx server, in the directory specified through the default configuration, (it is required to move the files into place manually before saving this commit, since `mkdocs build` puts its output in the `site/` directory, but IMO `html` is a more reasonable default location in the nginx buildpack.)

In terms of memory usage and concurrency, I think this version is more effective, and as far as machinery required for the automation, I think it's easier this way too, but both alternatives are still manual, so no need to reopen, the manual process is fine for now.  Here for posterity only!

Also, Happy New Year!

🎉 🌮
